name       : python-statsmodels
version    : 0.13.2
release    : 7
source     :
    - https://github.com/statsmodels/statsmodels/archive/refs/tags/v0.13.2.tar.gz : 2c37244a87d9116f9e7de134219fcecee947ffe43cb66b949ee6d0422edfb4cc
homepage   : https://www.statsmodels.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Statistical modeling and econometrics in Python
description: |
    statsmodels is a Python module that provides classes and functions for the estimation of many different statistical models, as well as for conducting statistical tests, and statistical data exploration.
builddeps  :
    - cython
    - python-pandas
    - python-patsy
rundeps    :
    - python-pandas
    - python-patsy
build      : |
    %python3_setup
install    : |
    %python3_install
