name       : python-statsmodels
version    : 0.9.0
release    : 2
source     :
    - https://github.com/statsmodels/statsmodels/archive/v0.9.0.tar.gz : 4ab219c776bf5b2187645c0ccb00cf8564c6c17541ae66ab96503f07368197d3
license    : BSD-3-Clause
component  : programming.python
summary    : Statistical modeling and econometrics in Python
description: |
    statsmodels is a Python module that provides classes and functions for
    the estimation of many different statistical models, as well as for
    conducting statistical tests, and statistical data exploration.
builddeps  :
    - cython
    - python-pandas
    - python-patsy
rundeps    :
    - python-pandas
    - python-patsy
build      : |
    %python3_setup
install    : |
    %python3_install
